### ISSUE TITLE
Can't build vibe.d 0.7.24 unittest-cov

### ISSUE THREAD

**Issue by alexeibs** [rejectedsoftware/vibe.d#1217] opened 2015-08-11 10:24 UTC
I got this error with DMD 2.068 on Travis and the same on my computer on Windows
```
.dub/packages/vibe-d-0.7.24/source/vibe/core/sync.d:97: undefined reference to `__coverage'
.dub/packages/vibe-d-0.7.24/source/vibe/core/sync.d:99: undefined reference to `__coverage'
.dub/packages/vibe-d-0.7.24/source/vibe/core/sync.d:101: undefined reference to `__coverage'
.dub/packages/vibe-d-0.7.24/source/vibe/core/sync.d:101: undefined reference to `__coverage'
```

**Comment by s-ludwig** [comment] 2016-02-02 12:19
Duplicate of #767.

**Closed by s-ludwig** 2016-02-02 12:19 UTC
