### ISSUE TITLE
option to have JsonSerializer ignore fields with null values

### ISSUE THREAD

**Issue by SingingBush** [rejectedsoftware/vibe.d#1619] opened 2016-11-10 16:05 UTC
currently the JsonSerializer will output json like this:

```javascript
{
    people: [
        {
            "id": 10,
            "name": "Dave",
            "email": null
        },
        {
            "id": 11,
            "name": "Susan",
            "email": "test@domain.com"
        },
        {
            "id": 12,
            "name": "Dave",
            "email": null
        }
    ]
}
```

it would be very handy for me if there was a setting to get to ignore the fields with nulls in them:

```javascript
{
    people: [
        {
            "id": 10,
            "name": "Dave"
        },
        {
            "id": 11,
            "name": "Susan",
            "email": "test@domain.com"
        },
        {
            "id": 12,
            "name": "Dave"
        }
    ]
}
```

Is there something in vibe-d to do this or will I need to write my own serializer?

**Comment by s-ludwig** [comment] 2016-11-10 16:16
Nothing built-in, but it probably makes sense to add something, as this has been requested before if I remember right. What you can do is to use custom `Json Person.toJson() const;` and `static Person Person.fromJson(Json);` methods that perform the conversion to Json manually. It means some manual serialization work, but it still integrates with the serializer, so that it can still be used in complex structures like above.

**Comment by tchaloupka** [comment] 2016-11-10 17:59
It's this request #1541

**Comment by crimaniak** [comment] 2016-11-11 06:26
I need this feature too, but I think we have better type - candidate to skip by default: undefined. Ideally it will be good to have some annotation to skip fields with defined values, for example `@toJsonSkip(Null, Undefined) string a;` or `@toJsonSkip(ZeroLength) string[] b;`
I don't know how to implement complete skip json nodes with current implementation of toJson(), I can only make undefined, so I made the next: struct JsonOptional with Nullable inside, generating undefined type node if value isNull, and then function jsonOptionalString() with ugly hack inside: generating json string and then removing undefined nodes with ctRegex. if here will be option in serializeToJson to skip undefined nodes completely it will be reasonable solution, still requiring class like JsonOptional, but simple to implement.
 
JsonOptional:
```d
struct JsonOptional(T)
{
	import std.typecons : Nullable;
	import vibe.data.json;

	Nullable!T value;
	
	this(T init){ value = Nullable!T(init); }
	
	// can't use alias this because of magic method toJson
	T get(){ return value.get; }
	bool isNull(){ return value.isNull; }
	void nullify() { value.nullify; }
	void opAssign(T newValue){ value = newValue; }
	
	Json toJson() const
	{
		import std.traits;
		static if(isArray!T) // skip empty array if applied to array
		{
			return value.isNull || value.get.length==0 ? Json.undefined() : serializeToJson(value.get);
		}
		else 
			return value.isNull ? Json.undefined() : serializeToJson(value.get);	
	}
	
	static JsonOptional!T fromJson(Json src)
	{
		return JsonOptional(Nullable!T(deserializeJson!T(src)));	
	}
}
```
usage:
```d
	struct Email
	{
		string email;
		JsonOptional!string name;
	}

	Email e = {email : "example@example.org"};
	assert(e.jsonOptionalString == "{email:\"example@example.org\"}");
```

**Comment by s-ludwig** [comment] 2016-11-11 07:00
Skipping undefined nodes needs to be done anyway (currently a bug), so that solution should definitely be possible. I think instead of explicitly telling the serializer what to skip, using the value of the default initializer is the cleaner solution, because it ensures that serialization is always properly reversible. However, there is some ambiguity in that definition for nested types...

I'll close this as a duplicate of #1541 for now (we can continue to discuss there).

**Closed by s-ludwig** 2016-11-11 07:00 UTC
