### ISSUE TITLE
openssl 1.1.0 binding issue

### ISSUE THREAD

**Issue by burner** [rejectedsoftware/vibe.d#1758] opened 2017-05-12 10:09 UTC
Openssl made the jump to 1.1.0 they removed some symbols. Which makes it impossible to use on arch linux without some non sustainable hacks.

`CRYPTO_num_locks'
`CRYPTO_set_id_callback'
`CRYPTO_set_locking_callback'
`SSL_get_ex_new_index'
`SSL_library_init'
`SSL_load_error_strings'
`SSLv23_client_method'
`SSLv23_server_method'

deimos is out of date and without git version tags.
I looked into creating bindings with dstep, but thats gone be a real pain.
IMHO it might be easier to create the definitions we need from openssl ourself and drop the deimos binding. Comments?

**Comment by wilzbach** [comment] 2017-05-12 10:21
> Openssl made the jump to 1.1.0 they removed some symbols. Which makes it impossible to use on arch linux without some non sustainable hacks.

There are two simple "hacks" to solve the problem temporarily:
- `versions "Have_Botan"`
- `versions "VibeNoSSL"` (use Nginx etc. as reverse proxy)

**Comment by burner** [comment] 2017-05-12 11:31
requestHTTP might need https as well. I'm not sure how to use nginx for that.
At some point we need update openssl or drop it. And dropping it is not really an option IMO.

**Comment by s-ludwig** [comment] 2017-05-12 11:41
Are there any known examples of how to properly achieve the same effect that those functions have with 1.1.x? To be honest that's the main roadblock - documentation is awful, code is awful and it's more or less impossible to get the initialization sequence right without an example.

Updating the Deimos headers indeed doesn't sound like fun. The huge mess that the OpenSSL code base is presumably makes that quite a PITA. BTW, I had to [clone the Deimos repository](https://github.com/s-ludwig/openssl) anyway to be able to make version tags a reality. There have been no responses in the main repository.

**Comment by burner** [comment] 2017-05-12 12:44
yeah openssl init looks like a big mess.
void SSL_load_error_strings() {} does not do anything anymore for example

I might have some time on Sunday to see if I can get dstep+vim to get a new version up and running

**Comment by CyberShadow** [comment] 2017-05-12 15:26
> There have been no responses in the main repository.

Just ping someone (with the necessary privileges), sheesh :)

**Comment by CyberShadow** [comment] 2017-05-12 15:26
FWIW, I would certainly be thankful for an update to the Deimos bindings, since I use those in `ae`! Right now I have to link DFeed against openssl 1.0.0 explicitly.

**Comment by MartinNowak** [comment] 2017-08-03 09:48
Duplicate of #1748

**Closed** 2017-08-12 10:33 UTC
