### ISSUE TITLE
WebSocket crashes when a connection gets closed

### ISSUE THREAD

**Issue by d-sobczyk** [rejectedsoftware/vibe.d#1724] opened 2017-03-26 14:31 UTC
Recently I encountered a problem with WebSockets. Our server application crashes with the following callstack:

```
[EB19FFA5:00000000 dbg] Socket event on fd 10: 33 (21178C8 vs 21178C8)
[EB19FFA5:EB1A17A5 dbg] TCP close request true open
[EB19FFA5:00000000 ERR] Task terminated with unhandled exception: Trying to acquire a TCP connection that is currently owned.
[EB19FFA5:00000000 dbg] Full error: core.exception.AssertError@../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/core/drivers/libevent2_tcp.d(145): Trying to acquire a TCP connection that is currently owned.
[EB19FFA5:00000000 dbg] ----------------
[EB19FFA5:00000000 dbg] ??:? _d_assert_msg [0x965f92]
[EB19FFA5:00000000 dbg] ../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/core/drivers/libevent2_tcp.d:145 void vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection.acquire() [0x8c9931]
[EB19FFA5:00000000 dbg] ../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/core/drivers/libevent2_tcp.d:188 void vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection.close() [0x8c9dd9]
[EB19FFA5:00000000 dbg] ../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/stream/wrapper.d:111 void vibe.stream.wrapper.ConnectionProxyStream.close() [0x90b78a]
[EB19FFA5:00000000 dbg] ../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/http/websockets.d:547 void vibe.http.websockets.WebSocket.startReader() [0x875668]
[EB19FFA5:00000000 dbg] ../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/core/core.d:592 void vibe.core.core.makeTaskFuncInfo!(void delegate()).makeTaskFuncInfo(ref void delegate()).callDelegate(vibe.core.core.TaskFuncInfo*) [0x799c24]
[EB19FFA5:00000000 dbg] ../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/core/core.d:1221 void vibe.core.core.CoreTask.run() [0x8bcde2]
[EB19FFA5:00000000 dbg] ??:? void core.thread.Fiber.run() [0x9c10a7]
[EB19FFA5:00000000 dbg] ??:? fiber_entryPoint [0x9c0e0a]
[EB19FFA5:00000000 dbg] ??:? [0xffffffff]
core.exception.AssertError@../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/core/drivers/libevent2_tcp.d(145): Trying to acquire a TCP connection that is currently owned.
----------------
??:? _d_assert_msg [0x965f92]
../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/core/drivers/libevent2_tcp.d:145 void vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection.acquire() [0x8c9931]
../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/core/drivers/libevent2_tcp.d:188 void vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection.close() [0x8c9dd9]
../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/stream/wrapper.d:111 void vibe.stream.wrapper.ConnectionProxyStream.close() [0x90b78a]
../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/http/websockets.d:547 void vibe.http.websockets.WebSocket.startReader() [0x875668]
../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/core/core.d:592 void vibe.core.core.makeTaskFuncInfo!(void delegate()).makeTaskFuncInfo(ref void delegate()).callDelegate(vibe.core.core.TaskFuncInfo*) [0x799c24]
../../../.dub/packages/vibe-d-0.7.30/vibe-d/source/vibe/core/core.d:1221 void vibe.core.core.CoreTask.run() [0x8bcde2]
??:? void core.thread.Fiber.run() [0x9c10a7]
??:? fiber_entryPoint [0x9c0e0a]
??:? [0xffffffff]
[EB19FFA5:00000000 dia] Main thread exiting
```

Two application are needed to reproduce the problem locally. The first one acts like a WebSocket server and sends periodically messages to its clients, the second application. Writing to the WebSocket connection is done in a separate task. Here is the source code for the server:

```
void main() {
  ubyte[] msg = new ubyte[1024*1024*2];
  ManualEvent event = createManualEvent();

  void handleClient(scope WebSocket socket) {
    auto writer = runTask({
      while (socket.connected) {
        socket.send(cast(string)msg);
        event.wait();
      }
    });

    while (socket.waitForData()) {
      socket.receiveText();
    }

    writer.join();
  }

  auto router = new URLRouter;
  router.get("/live", handleWebSockets(&handleClient));

  auto settings = new HTTPServerSettings;
  settings.bindAddresses = ["127.0.0.1"];
  settings.port = 8080;

  listenHTTP(settings, router);

  runTask({
    for (;;) {
      event.emit();
      sleep(100.msecs);
    }
  });

  runEventLoop();
}
```
The implementation of the server resembles our production server application that was crashing. In the real server, the `event.emit()` loop is a loop that receives messages from another service, with the frequency of two to three messages a second. The important part is the size of the message sent to WebSocket clients.

Here is the source code of the client (just to simulate web browser).

```
void main() {
    void connectToWS() {
      auto ws = connectWebSocket(URL("ws://127.0.0.1:8080/live"));
      while (ws.waitForData()) {
        ws.receiveText;
        throw new Error("");
      }
    }

    runTask(() => connectToWS());
    runEventLoop();
}
```

In order to reproduce the crash, it is best to run multiple clients at once. Perhaps even multiple times. For example:
```for i in `seq 10`; do ./client -c &; done```

The question is, am I doing something wrong? If no, is there any workaround for the problem until the fix is implemented?

**Comment by s-ludwig** [comment] 2017-03-27 13:21
I could observe two issues locally. One was a segfault within `fclose` due to a null pointer being passed to it. From the code it's not quite clear why that happened, but I suspect some kind of GC induced race condition, maybe also because some `Error` thrown within a GC context didn't terminate the process. I've adjusted the code to only create a single RNG instance per thread, which is much better anyway and couldn't reproduce this symptom anymore.

The other issue is "uncaught exception dwarfeh(224) fatal error" or most of the time just an exit code of 255 with an unknown uncaught exception within a task. I get similar issues on my production sites, but was never able to reproduce it consistently. Related DMD/Druntime issue: https://issues.dlang.org/show_bug.cgi?id=17271

This is the full snippet I used to reproduce this:
```
/++ dub.sdl:
  name "test"
  dependency "vibe-d" version="~>0.8.0-beta"
+/
import vibe.core.core;
import vibe.http.server;
import vibe.http.websockets;
import vibe.http.router;
import vibe.inet.url;
import core.time;

void main() {
  ubyte[] msg = new ubyte[1024*1024*2];
  ManualEvent event = createManualEvent();

  void handleClient(scope WebSocket socket) {
    auto writer = runTask({
      while (socket.connected) {
        socket.send(cast(string)msg);
        event.wait();
      }
    });

    while (socket.waitForData()) {
      socket.receiveText();
    }

    writer.join();
  }

  auto router = new URLRouter;
  router.get("/live", handleWebSockets(&handleClient));

  auto settings = new HTTPServerSettings;
  settings.bindAddresses = ["127.0.0.1"];
  settings.port = 8080;

  listenHTTP(settings, router);

  runTask({
    for (;;) {
      event.emit();
      sleep(100.msecs);
    }
  });

  foreach (i; 0 .. 1000)
    runWorkerTask(&connectToWS);

  runEventLoop();
}

void connectToWS() {
  auto ws = connectWebSocket(URL("ws://127.0.0.1:8080/live"));
  while (ws.waitForData()) {
    ws.receiveText;
    throw new Error("");
  }
}
```

**Comment by s-ludwig** [comment] 2017-03-27 14:36
Just noticed now that `connectToWS` throws an `Error` and not an `Exception`. In this case the application should actually get terminated immediately. I need to look into why this doesn't happen.

**Comment by d-sobczyk** [comment] 2017-03-27 16:17
Running your example gives the same result you mentioned, but for me, it is completely different from the problem where there are multiple processes involved. There is an assertion raised in the server application within acquire() method called from close() method of the Libevent2TCPConnection class. It is important to have a large buffer to send to the WebSocket client in order to reproduce the assertion.

**Comment by s-ludwig** [comment] 2017-03-29 07:13
The master branch now contains a fix for #1726, which appeared to be the reason for issues in my tests. Can you confirm that this has fixed it for you, too (using `"~master"` for vibe-d + `dub upgrade`)?

**Comment by d-sobczyk** [comment] 2017-03-29 15:31
Now, the server application itself doesn't crash, but the task itself is getting terminated with the following message: "Task terminated with uncaught exception: Connection error while writing to TCPConnection.". It seems that the following line in the server implementation:
```
socket.send(cast(string)msg);
```
is still getting called. Is this a desirable behavior?

**Comment by s-ludwig** [comment] 2017-03-29 15:44
I'd say that this is a classical race condition. It can happen that the connection is terminated faster than the next loop iteration is entered, but usually I'd expect the next `send` to start before the closing frame has been fully transferred. So based on that, the behavior appears to be correct.

**Comment by d-sobczyk** [comment] 2017-03-30 16:50
Personally, I do not think that the following code should ever throw:
```
if (socket.connected)
  socket.send(data);
```
It is definitely not something that a user of the library would expect. If you insist on leaving the solution as is, I would recommend to at least mention such behavior in the documentation.

**Comment by d-sobczyk** [comment] 2017-03-30 16:56
Is the fix going to be included in 0.7.31 version of vibe.d?

**Comment by s-ludwig** [comment] 2017-04-01 19:05
> Personally, I do not think that the following code should ever throw:
> 
>     if (socket.connected)
>       socket.send(data);
> It is definitely not something that a user of the library would expect. If you insist on leaving the solution as is, I would recommend to at least mention such behavior in the documentation.

There are a few things that can go wrong there. Most importantly, there is generally no upfront guarantee that sending on a socket will succeed. Also, in contrast to `.empty`, `.connected` does not block until an immediate write is possible, but instead returns the (outgoing) connection state immediately. This means that even for small packets, `.send` may block on the first TCP socket write, and basically any blocking operation can fail in some way (e.g. the connection may get terminated during this time or the task could get interrupted).

I'll keep a note to explain this better in the documentation.

> Is the fix going to be included in 0.7.31 version of vibe.d?

Not in 0.7.31, because the release is already too close, but I can tag an early 0.7.32-alpha.1  to make it available anyway.

**Comment by d-sobczyk** [comment] 2017-04-02 05:20
So basically, the `socket.connected` check doesn't make any sense in this case and clients should rely on exceptions being thrown from the `socket.send` instead. Unfortunately, every example on the Internet I have seen was written in this way, suggesting that the approach is correct, including the ones in vibe.d. It is also in some way funny that no one has ever run into such problems. I thought it is rather usual scenario.

Please, tag the alpha version. Thank you for your support and all the work done with vibe.d.

**Comment by s-ludwig** [comment] 2017-04-02 10:36
Not necessarily. The `connected` check will still make sure that under "normal" circumstances there will be no exception thrown. "Normal circumstances" meaning that the peer accepts all data that gets sent, which requires a communication protocol that signals an upcoming connection termination beforehand. If the peer can, on the other hand, regularly disconnect at any time, the exception is unavoidable\* and `while (connected)` could as well be replaced with `while (true)`.

Also, functionally, there will be no difference, but exceptions are always slower than a simple loop condition and it makes sense to avoid them on the "good path" just for that reason alone.

\* At least for web sockets, for raw TCP connections, the new stream API has `IOMode.once`, which can write partial buffer contents without throwing an exception.

**Comment by d-sobczyk** [comment] 2017-04-05 15:05
When the mentioned 0.7.32-alpha.1 tag that includes the bug fix can be expected? Sorry for bothering you, but it is important for me to have vibe.d version without this bug that I can reference in dub.json. I think that using master for production is not a good idea.

**Comment by s-ludwig** [comment] 2017-04-05 15:33
0.7.31 should be out on Monday. I can tag 0.7.32-alpha.1 immediately afterwards.

**Comment by s-ludwig** [comment] 2017-04-12 13:09
`v0.7.32-alpha.1` has been tagged and the throwing behavior description has been clarified now.

**Closed** 2017-04-16 19:29 UTC
