### ISSUE TITLE
Behavior of ConnectionStream.waitForData is unclear

### ISSUE THREAD

**Issue by mfrischknecht** [rejectedsoftware/vibe.d#1326] opened 2015-11-07 22:14 UTC
I have been looking at [ConnectionStream.waitForData()] on TCPConnection objects and found that the API documentation is not clear on some corner cases. After testing the behavior with a [simple test], it seems that the according behavior differs between backends<sup>1</sup>. 

Naively looking at the method, I would expect about the following behavior:
 1. If the method is passed a timeout of `0L` (the default value), it will wait indefinitely (since [InputStream.dataAvailableForRead] already delivers the information without the wait)
 2. If the connection is "empty" and gets closed, it will return false immediately (before the timeout occurs, not blocking up the fiber)
 3. If the connection contains unread data (whether it's still open or not), it returns true immediately

An implementation like this would basically allow for the most convenient loop that allows waiting for data:

```{D}
while(connection.waitForData(timeout))
{
    ubyte[] buffer = new ubyte[](connection.leastSize);
    connection.read(buffer);
    //Do stuff...
}
//Connection was closed or timed out
//All available data has been read
```

On a similar note, the maximum timeout of the method is not specified. Libasync seems to use `Duration.max` as the default value, whereas Libevent will throw exceptions stating that `int.max.seconds` is the maximum.

[ConnectionStream.waitForData()]: http://vibed.org/api/vibe.core.stream/ConnectionStream.waitForData
[simple test]: https://github.com/mfrischknecht/test-vibed-waitForData
[InputStream.dataAvailableForRead]: http://vibed.org/api/vibe.core.stream/InputStream.dataAvailableForRead

<sup>1</sup> On my Linux box, I was only able to build the Libevent and Libasync versions. Libev results in an error about a missing deimos module. Also, the behavior on Windows would be interesting to know, too.

Here's the behavior I observed:

##### Libevent
 1. Is not the case (waitForData(0L) returns immediately)
 2. True
 3. True

##### Libasync
 1. True
 2. True
 3. The test fails for a reason I can't explain. The socket I use won't transfer its payload although I use the flush() method explicitly (is this worth another issue?).

**Edit:**
##### win32
 1. True
 2. True
 3. True

**Comment by s-ludwig** [comment] 2015-11-11 10:09
Fixed now on all platforms. There is a [test](https://github.com/rejectedsoftware/vibe.d/blob/ca3e23c3c03e1d3d89a5a99c48ef6377930d6f94/tests/tcp/source/app.d#L18) and [documented behavior](https://github.com/rejectedsoftware/vibe.d/blob/ca3e23c3c03e1d3d89a5a99c48ef6377930d6f94/source/vibe/core/stream.d#L175) now, too. Still waiting for Travis to pass.

**Comment by s-ludwig** [comment] 2015-11-11 10:31
Looking good!

**Comment by s-ludwig** [comment] 2015-11-11 10:41
Just noticed that I'm not able to reproduce the libasync issue (#1330). Can you have a look at the test?

**Comment by etcimon** [comment] 2015-11-11 12:23
I could reproduce it on Windows, does it pass on linux without the fix?

**Comment by s-ludwig** [comment] 2015-11-11 12:33
At least the test that I added passes for me on both, Windows and Linux. Did you do anything else for reproducing it?

**Comment by etcimon** [comment] 2015-11-11 12:42
Strange, the waitForData should return false after the 10s timeout because the buffer is destroyed when the connection is closed. So, the test not passing is actually a failure in some sort.

**Comment by s-ludwig** [comment] 2015-11-11 12:54
Oh, now I see. I overlooked the test from the beginning. I'll add a "half-closed with pending data" test to the test suite, too.

**Comment by etcimon** [comment] 2015-11-11 12:54
Could you enable log in libasync.types and put it in a gist?

**Comment by s-ludwig** [comment] 2015-11-11 13:11
I've added the test now and libasync fails for me now as expected. I also understand the fix in #1330 now, but the destruction of the buffer is still in the wrong place, as `finalize` is an `OutputStream` operation, but the read buffer belongs to the `InputStream` part. IMO, the destruction should happen in `close()` and possibly also in `read` when it detects that the last bytes have been read.

**Comment by etcimon** [comment] 2015-11-11 13:24
> IMO, the destruction should happen in close() and possibly also in read when it detects that the last bytes have been read.

I think that would be close, because that's actually called by both the client and the server when really finished

**Closed** 2015-11-11 14:39 UTC

**Comment by s-ludwig** [comment] 2015-11-11 17:15
Okay, works for me now on Linux, but results in an `InvalidMemoryOperationError` on Windows during shutdown. Removing the calls to `close()` makes the errors go away, but I currently have no clue what causes it. Maybe something within libasync.

**Comment by etcimon** [comment] 2015-11-11 17:22
It closes the sockets in the destructor if it wasn't closed already. When the socket closes, it tries to resume tasks that have yielded and make them throw an exception. I think the `onClose` in `LibasyncTCPConnection.~this` might be preventative and unnecessary, removing that would fix the issue.

**Comment by s-ludwig** [comment] 2015-11-11 17:37
Hm, okay it's actually the receive buffer of the `TCPConnection` instances on the listening/server side. I've fixed it by replacing the call to `if (inbound) onClose()` in `onConnect` with a call to `close()` (which destroys the buffer). Do you see potential issues with that solution?

**Comment by etcimon** [comment] 2015-11-11 17:43
I thought the server called `close` in the vibe.http.server handler but if it doesn't, this is the best place to do it

**Comment by s-ludwig** [comment] 2015-11-11 17:43
BTW, maybe instead of using `FixedRingBuffer.freeOnDestruct` it is a better idea to add a `.deletePayload()` method and remove the `~this()` member altogether. I unfortunately missed this issue back when this was added.

**Comment by etcimon** [comment] 2015-11-11 18:01
Yes, I can't remember what prevented me from manually allocating the buffer. I replaced this by the memutils.circularbuffer which is manually allocated
