### ISSUE TITLE
diet: inline syntax for nested tags

### ISSUE THREAD

**Issue by MartinNowak** [rejectedsoftware/vibe.d#1278] opened 2015-09-28 10:29 UTC
Jade provides an abbreviated inline syntax for nested tags which is nice for boilerplate html elements.
```
a: img
a(href="#"): img
```

Also see http://jade-lang.com/reference/tags/

**Comment by s-ludwig** [comment] 2015-09-28 10:33
Duplicate of #33. I'll probably implement this in the context of a completely new Diet compiler that is separated into parser, DOM and generator parts. Hopefully, the compiler (CTFE) enhancements that have happened over the years make this possible and hopefully it won't eat up too much RAM during compilation. I already have this new implementation about 80% finished, but it's not yet public.

**Closed by s-ludwig** 2015-09-28 10:33 UTC

**Comment by MartinNowak** [comment] 2015-09-29 12:40
> Hopefully, the compiler (CTFE) enhancements that have happened over the years make this possible and hopefully it won't eat up too much RAM during compilation.

We still need to implement a proper AST interpreter, so don't expect too much.
