### ISSUE TITLE
dub config: need libs "zlib"

### ISSUE THREAD

**Issue by denizzzka** [rejectedsoftware/vibe.d#1458] opened 2016-03-18 12:52 UTC
With dependency "vibe-d:http" in my own project linker complains that zlib is not found. zlib used in vibe.stream.zlib

**Comment by s-ludwig** [comment] 2016-03-18 16:02
That's true, this is required for HTTP GZIP/ZLIB compression. This is usually automatically linked by the D compiler, because Phobos uses it, too. Do you bypass the compiler and link directly?

**Comment by denizzzka** [comment] 2016-03-19 01:48
> This is usually automatically linked by the D compiler, because Phobos uses it, too.

On my Debian system dmd does it, but ldc isn't (ldc package ver 1:0.17.0~beta2-1).

> Do you bypass the compiler and link directly?

Only dub --compiler=ldc2 option

**Comment by s-ludwig** [comment] 2016-07-11 16:02
Related thread: https://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/31256/

**Comment by s-ludwig** [comment] 2016-07-11 16:06
Should be fixed on master by 9df23d49. I couldn't reproduce the linker error with the LDC binaries from GitHub, so please reopen if necessary.

**Closed by s-ludwig** 2016-07-11 16:06 UTC
