### ISSUE TITLE
duplicate symbol under ldc 1.1.0-beta2

### ISSUE THREAD

**Issue by yannick** [rejectedsoftware/vibe.d#1589] opened 2016-10-07 15:12 UTC
when compiling with ldc i get

```
duplicate symbol __D4vibe4data4json4Json8toStringMFNeMDFNfAxaZvS3std6format18__T10FormatSpecTaZ10FormatSpecZ10DummyRange6__initZ in:
    ../vibe.d/libvibe-d_http.a(vibe.http.server.o)
    ../vibe.d/libvibe-d_redis.a(vibe.db.redis.redis.o)
duplicate symbol __D4vibe4data4json4Json8toStringMFNeMDFNfAxaZvS3std6format18__T10FormatSpecTaZ10FormatSpecZ10DummyRange6__initZ in:
    ../vibe.d/libvibe-d_http.a(vibe.http.server.o)
    ../vibe.d/libvibe-d_data.a(vibe.data.json.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/gcc failed with status: 1
ldc2 failed with exit code 1.
```

**Comment by s-ludwig** [comment] 2016-11-10 07:32
Could be a name mangling issue. Although it's not clear if this is the cause here, there are two slightly different definitions of `DummyRange` within two `toString` methods that differ only by the `@safe`ty of the callback argument, as well as their own safety. I've renamed one of the definitions on master now. Can you check if that fixed it for you?

**Comment by s-ludwig** [comment] 2016-12-19 13:09
Closing for now, since it compiles successfully for me locally, as well as on Travis-CI (1.0.0 and 1.1.0-beta6). Please re-open if this still occurs.

**Closed by s-ludwig** 2016-12-19 13:09 UTC
Labels: needs input
