### ISSUE TITLE
requestHTTP with HTTPS leaks file descriptors

### ISSUE THREAD

**Issue by devebookingservices** [rejectedsoftware/vibe.d#1244] opened 2015-09-02 14:22 UTC
It seems requestHTTP is leaking file descriptors when requesting through HTTPS.

My web service does an HTTPS client request, per request, and after a while, I started getting "Too many files open" error. netstat reveals an enormous amount of open sockets on port 443 in CLOSE_WAIT state.

The request used to be HTTP only and everything was fine, so it must be HTTPS only.

My workaround was to send the header: "Connection: close", and explicitly disconnect at the end of the response handler.

This is DMD 2.068.0, vibe 0.7.24 and libevent driver and Linux.

**Comment by etcimon** [comment] 2015-09-02 14:30
Can you test with DMD 2.067.1 ? See this issue: https://github.com/rejectedsoftware/vibe.d/issues/1240

**Comment by MartinNowak** [comment] 2015-09-11 17:52
Any update on that?

**Comment by marcioapm** [comment] 2015-09-11 17:53
I have been on vacation and unable to test this.
Will update you mid next-week.

**Comment by marcioapm** [comment] 2015-09-16 09:50
Hi! I rebuilt with 2.067.1, without the workaround, put on our live servers and in the first 2 minutes there were already over 100 of these leaked descriptors. In contrast the server built with the workaround, had been up for 8 days and had only 4-5, as expected.

Went back and tried 2.067.0, the earliest in the dlang.org archive, and it still leaks.

So yeah, if it is indeed a compiler regression, it's from earlier than 2.067.0

**Comment by marcioapm** [comment] 2015-09-16 10:45
Just tried 2.068.1 and it doesn't even run:

FATAL] Worker thread terminated due to uncaught error: No event driver loaded. Did the vibe.core.core module constructor run?

I'm not sure this is related to my setup or not, but the distance between working and not workign is a simple "dpkg -i "

2.068.0 works fine.

**Comment by marcioapm** [comment] 2015-09-16 19:10
@MartinNowak The second issue with the module constructor is fixed in 2.068.2-b2, but the leak still occurs...

**Comment by MartinNowak** [comment] 2015-09-27 12:39
The leak should be fixed with 2.068.2.

**Comment by s-ludwig** [comment] 2017-07-05 15:46
Did this indeed turn out to be fixed with 2.068.2? I just checked the dub registry process which performs lots of HTTPS requests, and everything looks clean there.

**Comment by devebookingservices** [comment] 2017-07-05 16:06
Hi Sönke,

We don't know. We have been using nginx in front of our app to handle HTTPS
and static files since then.

Thanks for coming back to us anyways.

Best,
-Jonas

**Comment by s-ludwig** [comment] 2017-07-05 16:08
Okay, thanks for the note! I'll close this issue then.

**Closed by s-ludwig** 2017-07-05 16:08 UTC
Labels: http
