### ISSUE TITLE
http server fails to parse IPv6 address in host header

### ISSUE THREAD

**Issue by MartinNowak** [rejectedsoftware/vibe.d#1391] opened 2016-02-01 20:48 UTC
`curl [::1]:8080`
Parsing of `HOST: [::1]:8080` fails here https://github.com/rejectedsoftware/vibe.d/blob/aaf32d4f6dd8c500648d22d915470a883ae56c6e/source/vibe/http/server.d#L1652.

**Comment by s-ludwig** [comment] 2016-02-02 07:20
Duplicate of #1388.

**Closed by s-ludwig** 2016-02-02 07:20 UTC
Labels: bug, duplicate
