### ISSUE TITLE
Linux: Second build with libasync yields a libevent linked application

### ISSUE THREAD

**Issue by stonemaster** [rejectedsoftware/vibe.d#1418] opened 2016-02-11 15:35 UTC
I have a simple test project created with `dub init vibe.d`. When `vibe.d` is not available (clean build environment e.g.) using libasync in dub.sdl doesn't have a dependency to libevent

***dub.sdl:***
```subConfiguration "vibe-d" "libasync"```

```
$ dub build
[...]
Using Linux EPOLL for events
vibe-d:utils 0.7.27: building configuration "library"...
vibe-d:data 0.7.27: building configuration "library"...
vibe-d:core 0.7.27: building configuration "libasync"...
Enhanced memory security is enabled.
Using Linux EPOLL for events
vibe-d:http 0.7.27: building configuration "library"...
Enhanced memory security is enabled.
Using Linux EPOLL for events
vibe-d:diet 0.7.27: building configuration "library"...
Enhanced memory security is enabled.
Using Linux EPOLL for events
vibe-d:mail 0.7.27: building configuration "library"...
Enhanced memory security is enabled.
Using Linux EPOLL for events
vibe-d:mongodb 0.7.27: building configuration "library"...
Enhanced memory security is enabled.
Using Linux EPOLL for events
vibe-d:redis 0.7.27: building configuration "library"...
Enhanced memory security is enabled.
Using Linux EPOLL for events
vibe-d:web 0.7.27: building configuration "library"...
Enhanced memory security is enabled.
Using Linux EPOLL for events
vibe-d 0.7.27: building configuration "libasync"...
Enhanced memory security is enabled.
Using Linux EPOLL for events
test ~master: building configuration "application"...
Enhanced memory security is enabled.
Using Linux EPOLL for events
```

And `ldd test` yields the fine version:

```
        linux-vdso.so.1 =>  (0x00007ffd4f7f8000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f975bf42000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f975bb00000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f975b8f7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f975b6d9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f975b3d1000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f975b1cc000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f975ae02000)
        /lib64/ld-linux-x86-64.so.2 (0x00005578007c2000)
```

But building the same project a second time it will be linked against ***libevent***. `dub build`:
```
Performing "debug" build using dmd for x86_64.
vibe-d:utils 0.7.27: building configuration "library"...
vibe-d:data 0.7.27: building configuration "library"...
vibe-d:core 0.7.27: building configuration "libevent"...
vibe-d:http 0.7.27: building configuration "library"...
vibe-d:diet 0.7.27: building configuration "library"...
vibe-d:mail 0.7.27: building configuration "library"...
vibe-d:mongodb 0.7.27: building configuration "library"...
vibe-d:redis 0.7.27: building configuration "library"...
vibe-d:web 0.7.27: building configuration "library"...
vibe-d 0.7.27: building configuration "libasync"...
test ~master: building configuration "application"...
Linking...
```

And so ...
```
$ ldd test
        linux-vdso.so.1 =>  (0x00007ffd9cf8f000)
        libevent_pthreads-2.0.so.5 => /usr/lib/x86_64-linux-gnu/libevent_pthreads-2.0.so.5 (0x00007f214ae02000)
        libevent-2.0.so.5 => /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5 (0x00007f214abbc000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f214a952000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f214a510000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f214a2f2000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2149fe9000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2149de1000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2149bdd000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2149812000)
        /lib64/ld-linux-x86-64.so.2 (0x00005605b45bd000)
        libevent_core-2.0.so.5 => /usr/lib/x86_64-linux-gnu/libevent_core-2.0.so.5 (0x00007f21495e8000)
```

I am running on Linux x64. DMD Version 2.069.2. Problem als persists with 2.070.0. Dub version 0.9.24

**Comment by jacob-carlborg** [comment] 2016-02-18 10:32
Building with the verbose flags shows that Dub is passing `-version=VibeLibeventDriver`

**Comment by jacob-carlborg** [comment] 2016-02-18 12:43
You can remove the `~/.dub/packages` directory as a workaround.

**Comment by s-ludwig** [comment] 2016-02-19 13:26
This was caused by D-Programming-Language/dub#745 (fixed on master).

**Closed** 2016-02-19 13:26 UTC
